// Package plugingen provides code generation tools for type-safe plugin boundaries.
package plugingen

// headerData contains data for the header template.
type headerData struct {
	PackageName string
	Description string
	PluginName  string
	Version     string
	Imports     []string
}

// structData contains data for the struct template.
type structData struct {
	Name   string
	Fields []*FieldDef
}

// fromMapData contains data for the FromMap template.
type fromMapData struct {
	TypeName string
	Fields   []*FieldDef
}

// toMapData contains data for the ToMap template.
type toMapData struct {
	TypeName string
	Fields   []*FieldDef
}

// headerTemplate generates the package header and imports.
const headerTemplate = `// Code generated by plugingen. DO NOT EDIT.
{{if .Description}}// {{.Description}}{{end}}
// Plugin: {{.PluginName}}
// Version: {{.Version}}

package {{.PackageName}}

import (
{{range .Imports}}	"{{.}}"
{{end}}
)

`

// structTemplate generates a struct definition.
const structTemplate = `
// {{.Name}} represents the plugin {{.Name | toLower}} structure.
type {{.Name}} struct {
{{range .Fields}}{{description .Description}}	{{.Name}} {{goType .Type}} {{jsonTag .}}
{{end}}}

`

// fromMapTemplate generates the FromMap conversion function.
const fromMapTemplate = `
// {{.TypeName}}FromMap converts a map[string]any to *{{.TypeName}}.
//
// This function performs type-safe conversion with validation for required fields.
func {{.TypeName}}FromMap(data map[string]any) (*{{.TypeName}}, error) {
	if data == nil {
		return nil, errors.New("input data is nil")
	}

	result := &{{.TypeName}}{}

{{range .Fields}}{{convertField .}}{{end}}
	return result, nil
}

`

// toMapTemplate generates the ToMap serialization function.
const toMapTemplate = `
// {{.TypeName}}ToMap converts a *{{.TypeName}} to map[string]any.
//
// This function performs type-safe serialization.
func {{.TypeName}}ToMap(v *{{.TypeName}}) map[string]any {
	if v == nil {
		return nil
	}

	result := make(map[string]any)

{{range .Fields}}{{serializeField .}}{{end}}
	return result
}

`
