// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/kart-io/sentinel-x",
        "contact": {
            "name": "Sentinel-X Team",
            "url": "https://github.com/kart-io/sentinel-x",
            "email": "support@sentinel-x.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/hello": {
            "get": {
                "description": "公开接口，返回欢迎消息（无需认证）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Demo"
                ],
                "summary": "Say Hello",
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_kart-io_sentinel-x_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api_handler.HelloResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "获取当前登录用户的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Demo"
                ],
                "summary": "Get Current User Profile",
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_kart-io_sentinel-x_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api_handler.ProfileResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/github_com_kart-io_sentinel-x_pkg_utils_response.Response"
                        }
                    }
                }
            }
        },
        "/protected": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "需要 JWT 认证的受保护资源",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Demo"
                ],
                "summary": "Protected Resource",
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_kart-io_sentinel-x_pkg_utils_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_api_handler.ProtectedResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/github_com_kart-io_sentinel-x_pkg_utils_response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_kart-io_sentinel-x_pkg_utils_response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code is the business error code (0 = success)",
                    "type": "integer"
                },
                "data": {
                    "description": "Data contains the response payload (nil for errors)"
                },
                "http_code": {
                    "description": "HTTPCode is the HTTP status code (optional, for client convenience)",
                    "type": "integer"
                },
                "message": {
                    "description": "Message is a human-readable message",
                    "type": "string"
                },
                "request_id": {
                    "description": "RequestID is the unique request identifier for tracing",
                    "type": "string"
                },
                "timestamp": {
                    "description": "Timestamp is the response timestamp (Unix milliseconds)",
                    "type": "integer"
                }
            }
        },
        "internal_api_handler.HelloResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Hello from Sentinel-X API!"
                },
                "version": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "internal_api_handler.ProfileResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "integer",
                    "example": 1735689600
                },
                "id": {
                    "type": "string",
                    "example": "user-123"
                },
                "issued_at": {
                    "type": "integer",
                    "example": 1735603200
                },
                "issuer": {
                    "type": "string",
                    "example": "sentinel-x"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "admin",
                        "user"
                    ]
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "internal_api_handler.ProtectedResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "This is a protected resource"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "admin",
                        "user"
                    ]
                },
                "user_id": {
                    "type": "string",
                    "example": "user-123"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "JWT Bearer token. Example: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8100",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Sentinel-X API",
	Description:      "Sentinel-X 平台 API 服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
