version: 2
run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

linters:
  disable-all: true
  enable:
    - revive
    - gosec
    - gocritic
    - gocyclo
    - dupl
    - goconst
    - misspell
    - unconvert
    - unparam

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

issues:
  exclude-dirs:
    - scripts
    - vendor
    - staging
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
