// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: pkg/api/rag/v1/rag.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndexFromURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexFromURLRequest) Reset() {
	*x = IndexFromURLRequest{}
	mi := &file_pkg_api_rag_v1_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexFromURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexFromURLRequest) ProtoMessage() {}

func (x *IndexFromURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_rag_v1_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexFromURLRequest.ProtoReflect.Descriptor instead.
func (*IndexFromURLRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_rag_v1_rag_proto_rawDescGZIP(), []int{0}
}

func (x *IndexFromURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_pkg_api_rag_v1_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_rag_v1_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_rag_v1_rag_proto_rawDescGZIP(), []int{1}
}

func (x *QueryRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Sources       []*ChunkSource         `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_pkg_api_rag_v1_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_rag_v1_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_rag_v1_rag_proto_rawDescGZIP(), []int{2}
}

func (x *QueryResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *QueryResponse) GetSources() []*ChunkSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

type ChunkSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	DocumentName  string                 `protobuf:"bytes,2,opt,name=document_name,json=documentName,proto3" json:"document_name,omitempty"`
	Section       string                 `protobuf:"bytes,3,opt,name=section,proto3" json:"section,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Score         float32                `protobuf:"fixed32,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkSource) Reset() {
	*x = ChunkSource{}
	mi := &file_pkg_api_rag_v1_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkSource) ProtoMessage() {}

func (x *ChunkSource) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_rag_v1_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkSource.ProtoReflect.Descriptor instead.
func (*ChunkSource) Descriptor() ([]byte, []int) {
	return file_pkg_api_rag_v1_rag_proto_rawDescGZIP(), []int{3}
}

func (x *ChunkSource) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ChunkSource) GetDocumentName() string {
	if x != nil {
		return x.DocumentName
	}
	return ""
}

func (x *ChunkSource) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *ChunkSource) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChunkSource) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	ChunkCount    int64                  `protobuf:"varint,2,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	EmbeddingDim  int32                  `protobuf:"varint,3,opt,name=embedding_dim,json=embeddingDim,proto3" json:"embedding_dim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_pkg_api_rag_v1_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_rag_v1_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_rag_v1_rag_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatsResponse) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *GetStatsResponse) GetChunkCount() int64 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *GetStatsResponse) GetEmbeddingDim() int32 {
	if x != nil {
		return x.EmbeddingDim
	}
	return 0
}

var File_pkg_api_rag_v1_rag_proto protoreflect.FileDescriptor

const file_pkg_api_rag_v1_rag_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/api/rag/v1/rag.proto\x12\x06rag.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"'\n" +
	"\x13IndexFromURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"*\n" +
	"\fQueryRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\"V\n" +
	"\rQueryResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12-\n" +
	"\asources\x18\x02 \x03(\v2\x13.rag.v1.ChunkSourceR\asources\"\x9d\x01\n" +
	"\vChunkSource\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12#\n" +
	"\rdocument_name\x18\x02 \x01(\tR\fdocumentName\x12\x18\n" +
	"\asection\x18\x03 \x01(\tR\asection\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x02R\x05score\"x\n" +
	"\x10GetStatsResponse\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x1f\n" +
	"\vchunk_count\x18\x02 \x01(\x03R\n" +
	"chunkCount\x12#\n" +
	"\rembedding_dim\x18\x03 \x01(\x05R\fembeddingDim2\x94\x02\n" +
	"\n" +
	"RAGService\x12a\n" +
	"\fIndexFromURL\x12\x1b.rag.v1.IndexFromURLRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/rag/index/url\x12N\n" +
	"\x05Query\x12\x14.rag.v1.QueryRequest\x1a\x15.rag.v1.QueryResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/rag/query\x12S\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x18.rag.v1.GetStatsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/rag/statsB.Z,github.com/kart/sentinel-x/pkg/api/rag/v1;v1b\x06proto3"

var (
	file_pkg_api_rag_v1_rag_proto_rawDescOnce sync.Once
	file_pkg_api_rag_v1_rag_proto_rawDescData []byte
)

func file_pkg_api_rag_v1_rag_proto_rawDescGZIP() []byte {
	file_pkg_api_rag_v1_rag_proto_rawDescOnce.Do(func() {
		file_pkg_api_rag_v1_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_rag_v1_rag_proto_rawDesc), len(file_pkg_api_rag_v1_rag_proto_rawDesc)))
	})
	return file_pkg_api_rag_v1_rag_proto_rawDescData
}

var file_pkg_api_rag_v1_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_api_rag_v1_rag_proto_goTypes = []any{
	(*IndexFromURLRequest)(nil), // 0: rag.v1.IndexFromURLRequest
	(*QueryRequest)(nil),        // 1: rag.v1.QueryRequest
	(*QueryResponse)(nil),       // 2: rag.v1.QueryResponse
	(*ChunkSource)(nil),         // 3: rag.v1.ChunkSource
	(*GetStatsResponse)(nil),    // 4: rag.v1.GetStatsResponse
	(*emptypb.Empty)(nil),       // 5: google.protobuf.Empty
}
var file_pkg_api_rag_v1_rag_proto_depIdxs = []int32{
	3, // 0: rag.v1.QueryResponse.sources:type_name -> rag.v1.ChunkSource
	0, // 1: rag.v1.RAGService.IndexFromURL:input_type -> rag.v1.IndexFromURLRequest
	1, // 2: rag.v1.RAGService.Query:input_type -> rag.v1.QueryRequest
	5, // 3: rag.v1.RAGService.GetStats:input_type -> google.protobuf.Empty
	5, // 4: rag.v1.RAGService.IndexFromURL:output_type -> google.protobuf.Empty
	2, // 5: rag.v1.RAGService.Query:output_type -> rag.v1.QueryResponse
	4, // 6: rag.v1.RAGService.GetStats:output_type -> rag.v1.GetStatsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_api_rag_v1_rag_proto_init() }
func file_pkg_api_rag_v1_rag_proto_init() {
	if File_pkg_api_rag_v1_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_rag_v1_rag_proto_rawDesc), len(file_pkg_api_rag_v1_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_rag_v1_rag_proto_goTypes,
		DependencyIndexes: file_pkg_api_rag_v1_rag_proto_depIdxs,
		MessageInfos:      file_pkg_api_rag_v1_rag_proto_msgTypes,
	}.Build()
	File_pkg_api_rag_v1_rag_proto = out.File
	file_pkg_api_rag_v1_rag_proto_goTypes = nil
	file_pkg_api_rag_v1_rag_proto_depIdxs = nil
}
