// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/hello/v1/hello.proto

package hello

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HelloRequest is the request message for SayHello.
type HelloRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the name to greet.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_pkg_api_hello_v1_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_hello_v1_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_hello_v1_hello_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// HelloResponse is the response message for SayHello.
type HelloResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message is the greeting message.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_pkg_api_hello_v1_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_hello_v1_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_hello_v1_hello_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_api_hello_v1_hello_proto protoreflect.FileDescriptor

const file_pkg_api_hello_v1_hello_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/api/hello/v1/hello.proto\x12\fapi.hello.v1\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\rHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa0\x01\n" +
	"\fHelloService\x12C\n" +
	"\bSayHello\x12\x1a.api.hello.v1.HelloRequest\x1a\x1b.api.hello.v1.HelloResponse\x12K\n" +
	"\x0eSayHelloStream\x12\x1a.api.hello.v1.HelloRequest\x1a\x1b.api.hello.v1.HelloResponse0\x01B6Z4github.com/kart-io/sentinel-x/pkg/api/hello/v1;hellob\x06proto3"

var (
	file_pkg_api_hello_v1_hello_proto_rawDescOnce sync.Once
	file_pkg_api_hello_v1_hello_proto_rawDescData []byte
)

func file_pkg_api_hello_v1_hello_proto_rawDescGZIP() []byte {
	file_pkg_api_hello_v1_hello_proto_rawDescOnce.Do(func() {
		file_pkg_api_hello_v1_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_hello_v1_hello_proto_rawDesc), len(file_pkg_api_hello_v1_hello_proto_rawDesc)))
	})
	return file_pkg_api_hello_v1_hello_proto_rawDescData
}

var (
	file_pkg_api_hello_v1_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
	file_pkg_api_hello_v1_hello_proto_goTypes  = []any{
		(*HelloRequest)(nil),  // 0: api.hello.v1.HelloRequest
		(*HelloResponse)(nil), // 1: api.hello.v1.HelloResponse
	}
)

var file_pkg_api_hello_v1_hello_proto_depIdxs = []int32{
	0, // 0: api.hello.v1.HelloService.SayHello:input_type -> api.hello.v1.HelloRequest
	0, // 1: api.hello.v1.HelloService.SayHelloStream:input_type -> api.hello.v1.HelloRequest
	1, // 2: api.hello.v1.HelloService.SayHello:output_type -> api.hello.v1.HelloResponse
	1, // 3: api.hello.v1.HelloService.SayHelloStream:output_type -> api.hello.v1.HelloResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_hello_v1_hello_proto_init() }
func file_pkg_api_hello_v1_hello_proto_init() {
	if File_pkg_api_hello_v1_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_hello_v1_hello_proto_rawDesc), len(file_pkg_api_hello_v1_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_hello_v1_hello_proto_goTypes,
		DependencyIndexes: file_pkg_api_hello_v1_hello_proto_depIdxs,
		MessageInfos:      file_pkg_api_hello_v1_hello_proto_msgTypes,
	}.Build()
	File_pkg_api_hello_v1_hello_proto = out.File
	file_pkg_api_hello_v1_hello_proto_goTypes = nil
	file_pkg_api_hello_v1_hello_proto_depIdxs = nil
}
