// Package rag Code generated by swaggo/swag. DO NOT EDIT
package rag

import "github.com/swaggo/swag"

const docTemplaterag = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/kart-io/sentinel-x",
        "contact": {
            "name": "Sentinel-X Team",
            "url": "https://github.com/kart-io/sentinel-x",
            "email": "support@sentinel-x.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/rag/collections": {
            "get": {
                "description": "返回当前系统中配置的所有知识库集合及其详细信息。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RAG"
                ],
                "summary": "列出所有知识库集合",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handler.CollectionInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/rag/evaluate": {
            "post": {
                "description": "使用评估器（通常是另一个 LLM）对生成的回答、检索的上下文进行评分。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RAG"
                ],
                "summary": "评估 RAG 回答质量",
                "parameters": [
                    {
                        "description": "评估请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.EvaluateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/evaluator.Result"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/rag/index": {
            "post": {
                "description": "下载并处理指定 URL 的文档，将其切片并存储到向量数据库中。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RAG"
                ],
                "summary": "从 URL 索引文档",
                "parameters": [
                    {
                        "description": "索引请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.IndexRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/rag/index/directory": {
            "post": {
                "description": "处理指定本地目录下的所有支持的文档，将其切片并存储到向量数据库中。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RAG"
                ],
                "summary": "从本地目录索引文档",
                "parameters": [
                    {
                        "description": "目录索引请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.IndexDirectoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/rag/index/url": {
            "post": {
                "description": "下载并处理指定 URL 的文档，将其切片并存储到向量数据库中。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RAG"
                ],
                "summary": "从 URL 索引文档 (别名)",
                "parameters": [
                    {
                        "description": "索引请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.IndexFromURLRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/rag/metrics": {
            "get": {
                "description": "返回 RAG 服务运行期间产生的各种业务指标（Prometheus 格式）。",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "RAG"
                ],
                "summary": "导出业务指标",
                "responses": {
                    "200": {
                        "description": "metrics data",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/rag/query": {
            "post": {
                "description": "根据用户提出的问题，从知识库中检索相关上下文，并生成回答。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RAG"
                ],
                "summary": "执行 RAG 查询",
                "parameters": [
                    {
                        "description": "查询请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.QueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.QueryResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "408": {
                        "description": "Request Timeout",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/rag/query-evaluate": {
            "post": {
                "description": "执行 RAG 查询流程，并在生成结果后立即进行质量评估。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RAG"
                ],
                "summary": "查询并即时评估",
                "parameters": [
                    {
                        "description": "查询评估请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.QueryAndEvaluateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.SuccessResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.QueryAndEvaluateResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/rag/stats": {
            "get": {
                "description": "返回当前向量数据库的集合名称、文本片段总数等统计数据。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RAG"
                ],
                "summary": "获取知识库统计信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "evaluator.Details": {
            "type": "object",
            "properties": {
                "claims": {
                    "description": "Claims 从答案中提取的声明列表。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "generated_questions": {
                    "description": "GeneratedQuestions 从答案生成的问题（用于答案相关性评估）。",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "relevant_contexts": {
                    "description": "RelevantContexts 相关上下文的索引列表。",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "supported_claims": {
                    "description": "SupportedClaims 被上下文支持的声明数量。",
                    "type": "integer"
                },
                "total_claims": {
                    "description": "TotalClaims 总声明数量。",
                    "type": "integer"
                }
            }
        },
        "evaluator.Result": {
            "type": "object",
            "properties": {
                "answer_relevancy": {
                    "description": "AnswerRelevancy 答案相关性评分 (0-1)，衡量答案与问题的相关程度。",
                    "type": "number"
                },
                "context_precision": {
                    "description": "ContextPrecision 上下文精确度评分 (0-1)，衡量检索上下文的相关性排名。",
                    "type": "number"
                },
                "context_recall": {
                    "description": "ContextRecall 上下文召回率评分 (0-1)，衡量检索内容覆盖理想答案的程度。",
                    "type": "number"
                },
                "details": {
                    "description": "Details 评估详情。",
                    "allOf": [
                        {
                            "$ref": "#/definitions/evaluator.Details"
                        }
                    ]
                },
                "faithfulness": {
                    "description": "Faithfulness 忠实度评分 (0-1)，衡量答案与上下文的事实一致性。",
                    "type": "number"
                },
                "overall_score": {
                    "description": "OverallScore 综合评分 (0-1)，所有指标的加权平均。",
                    "type": "number"
                }
            }
        },
        "handler.CollectionInfo": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 5000
                },
                "description": {
                    "type": "string",
                    "example": "RAG knowledge base collection"
                },
                "name": {
                    "type": "string",
                    "example": "milvus_docs"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "bad request"
                }
            }
        },
        "handler.EvaluateRequest": {
            "type": "object",
            "required": [
                "answer",
                "contexts",
                "question"
            ],
            "properties": {
                "answer": {
                    "type": "string",
                    "example": "RAG 是检索增强生成。"
                },
                "contexts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "['上下文片段1']"
                    ]
                },
                "ground_truth": {
                    "type": "string",
                    "example": "检索增强生成 (Retrieval-Augmented Generation)"
                },
                "question": {
                    "type": "string",
                    "example": "什么是 RAG？"
                }
            }
        },
        "handler.IndexDirectoryRequest": {
            "type": "object",
            "required": [
                "directory"
            ],
            "properties": {
                "directory": {
                    "type": "string",
                    "example": "/data/docs"
                }
            }
        },
        "handler.IndexFromURLRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "url": {
                    "type": "string",
                    "example": "https://milvus.io/docs/overview.md"
                }
            }
        },
        "handler.IndexRequest": {
            "type": "object",
            "required": [
                "source_url"
            ],
            "properties": {
                "source_url": {
                    "type": "string",
                    "example": "https://milvus.io/docs/overview.md"
                }
            }
        },
        "handler.QueryAndEvaluateRequest": {
            "type": "object",
            "required": [
                "question"
            ],
            "properties": {
                "ground_truth": {
                    "type": "string",
                    "example": "微服务平台"
                },
                "question": {
                    "type": "string",
                    "example": "Sentinel-X 是什么？"
                }
            }
        },
        "handler.QueryAndEvaluateResponse": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string",
                    "example": "回答内容"
                },
                "evaluation": {
                    "$ref": "#/definitions/evaluator.Result"
                },
                "sources": {}
            }
        },
        "handler.QueryRequest": {
            "type": "object",
            "required": [
                "question"
            ],
            "properties": {
                "question": {
                    "type": "string",
                    "example": "什么是 Milvus？"
                }
            }
        },
        "handler.SuccessResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {},
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.ChunkSource": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "document_id": {
                    "type": "string"
                },
                "document_name": {
                    "type": "string"
                },
                "score": {
                    "type": "number"
                },
                "section": {
                    "type": "string"
                }
            }
        },
        "model.QueryResult": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string"
                },
                "sources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ChunkSource"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "JWT Bearer token. Example: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInforag holds exported Swagger Info so clients can modify it
var SwaggerInforag = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Sentinel-X RAG API",
	Description:      "RAG 知识库服务 - 基于 Milvus 向量数据库和 Ollama LLM",
	InfoInstanceName: "rag",
	SwaggerTemplate:  docTemplaterag,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInforag.InstanceName(), SwaggerInforag)
}
