// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/api/user-center/v1/user.proto

package user

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_pkg_api_user_center_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_user_center_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_user_center_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_pkg_api_user_center_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_user_center_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_user_center_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_pkg_api_user_center_v1_user_proto protoreflect.FileDescriptor

const file_pkg_api_user_center_v1_user_proto_rawDesc = "" +
	"\n" +
	"!pkg/api/user-center/v1/user.proto\x12\vapi.user.v1\"\x1d\n" +
	"\vUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"N\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role2M\n" +
	"\vUserService\x12>\n" +
	"\aGetUser\x12\x18.api.user.v1.UserRequest\x1a\x19.api.user.v1.UserResponseB;Z9github.com/kart-io/sentinel-x/pkg/api/user-center/v1;userb\x06proto3"

var (
	file_pkg_api_user_center_v1_user_proto_rawDescOnce sync.Once
	file_pkg_api_user_center_v1_user_proto_rawDescData []byte
)

func file_pkg_api_user_center_v1_user_proto_rawDescGZIP() []byte {
	file_pkg_api_user_center_v1_user_proto_rawDescOnce.Do(func() {
		file_pkg_api_user_center_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_user_center_v1_user_proto_rawDesc), len(file_pkg_api_user_center_v1_user_proto_rawDesc)))
	})
	return file_pkg_api_user_center_v1_user_proto_rawDescData
}

var (
	file_pkg_api_user_center_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
	file_pkg_api_user_center_v1_user_proto_goTypes  = []any{
		(*UserRequest)(nil),  // 0: api.user.v1.UserRequest
		(*UserResponse)(nil), // 1: api.user.v1.UserResponse
	}
)

var file_pkg_api_user_center_v1_user_proto_depIdxs = []int32{
	0, // 0: api.user.v1.UserService.GetUser:input_type -> api.user.v1.UserRequest
	1, // 1: api.user.v1.UserService.GetUser:output_type -> api.user.v1.UserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_user_center_v1_user_proto_init() }
func file_pkg_api_user_center_v1_user_proto_init() {
	if File_pkg_api_user_center_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_user_center_v1_user_proto_rawDesc), len(file_pkg_api_user_center_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_user_center_v1_user_proto_goTypes,
		DependencyIndexes: file_pkg_api_user_center_v1_user_proto_depIdxs,
		MessageInfos:      file_pkg_api_user_center_v1_user_proto_msgTypes,
	}.Build()
	File_pkg_api_user_center_v1_user_proto = out.File
	file_pkg_api_user_center_v1_user_proto_goTypes = nil
	file_pkg_api_user_center_v1_user_proto_depIdxs = nil
}
