// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: pkg/api/scheduler/v1/scheduler.proto

package schedulerv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobType defines the type of the job.
type JobType int32

const (
	JobType_JOB_TYPE_UNSPECIFIED JobType = 0
	JobType_JOB_TYPE_HTTP        JobType = 1 // Execute an HTTP request
	JobType_JOB_TYPE_GRPC        JobType = 2 // Execute a gRPC call (future support)
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "JOB_TYPE_UNSPECIFIED",
		1: "JOB_TYPE_HTTP",
		2: "JOB_TYPE_GRPC",
	}
	JobType_value = map[string]int32{
		"JOB_TYPE_UNSPECIFIED": 0,
		"JOB_TYPE_HTTP":        1,
		"JOB_TYPE_GRPC":        2,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_scheduler_v1_scheduler_proto_enumTypes[0].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_pkg_api_scheduler_v1_scheduler_proto_enumTypes[0]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

// JobStatus represents the current state of a job.
type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_ENABLED     JobStatus = 1
	JobStatus_JOB_STATUS_DISABLED    JobStatus = 2
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_ENABLED",
		2: "JOB_STATUS_DISABLED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_ENABLED":     1,
		"JOB_STATUS_DISABLED":    2,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_scheduler_v1_scheduler_proto_enumTypes[1].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_pkg_api_scheduler_v1_scheduler_proto_enumTypes[1]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

type Job struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type        JobType                `protobuf:"varint,4,opt,name=type,proto3,enum=api.scheduler.v1.JobType" json:"type,omitempty"`
	Status      JobStatus              `protobuf:"varint,5,opt,name=status,proto3,enum=api.scheduler.v1.JobStatus" json:"status,omitempty"`
	// Cron expression (e.g., "0 * * * *")
	CronExpression string `protobuf:"bytes,6,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"`
	// Job payload (JSON string for HTTP body or gRPC data)
	Payload string `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	// Target execution endpoint (e.g., "http://user-center:8081/health")
	Target        string                 `protobuf:"bytes,8,opt,name=target,proto3" json:"target,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	NextRunTime   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=next_run_time,json=nextRunTime,proto3" json:"next_run_time,omitempty"`
	LastRunTime   *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_run_time,json=lastRunTime,proto3" json:"last_run_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_pkg_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Job) GetType() JobType {
	if x != nil {
		return x.Type
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

func (x *Job) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *Job) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *Job) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Job) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Job) GetNextRunTime() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunTime
	}
	return nil
}

func (x *Job) GetLastRunTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRunTime
	}
	return nil
}

type CreateJobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type           JobType                `protobuf:"varint,3,opt,name=type,proto3,enum=api.scheduler.v1.JobType" json:"type,omitempty"`
	CronExpression string                 `protobuf:"bytes,4,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"`
	Payload        string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Target         string                 `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateJobRequest) Reset() {
	*x = CreateJobRequest{}
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRequest) ProtoMessage() {}

func (x *CreateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRequest.ProtoReflect.Descriptor instead.
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *CreateJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateJobRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateJobRequest) GetType() JobType {
	if x != nil {
		return x.Type
	}
	return JobType_JOB_TYPE_UNSPECIFIED
}

func (x *CreateJobRequest) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *CreateJobRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *CreateJobRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type CreateJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobResponse) Reset() {
	*x = CreateJobResponse{}
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobResponse) ProtoMessage() {}

func (x *CreateJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobResponse.ProtoReflect.Descriptor instead.
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *CreateJobResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *ListJobsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListJobsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListJobsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UpdateJobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CronExpression string                 `protobuf:"bytes,4,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"`
	Payload        string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Target         string                 `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	Status         JobStatus              `protobuf:"varint,7,opt,name=status,proto3,enum=api.scheduler.v1.JobStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateJobRequest) Reset() {
	*x = UpdateJobRequest{}
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobRequest) ProtoMessage() {}

func (x *UpdateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateJobRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateJobRequest) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *UpdateJobRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *UpdateJobRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *UpdateJobRequest) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

type UpdateJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobResponse) Reset() {
	*x = UpdateJobResponse{}
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobResponse) ProtoMessage() {}

func (x *UpdateJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobResponse.ProtoReflect.Descriptor instead.
func (*UpdateJobResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateJobResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobRequest) Reset() {
	*x = DeleteJobRequest{}
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobRequest) ProtoMessage() {}

func (x *DeleteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobRequest.ProtoReflect.Descriptor instead.
func (*DeleteJobRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobResponse) Reset() {
	*x = DeleteJobResponse{}
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobResponse) ProtoMessage() {}

func (x *DeleteJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobResponse.ProtoReflect.Descriptor instead.
func (*DeleteJobResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteJobResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TriggerJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerJobRequest) Reset() {
	*x = TriggerJobRequest{}
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerJobRequest) ProtoMessage() {}

func (x *TriggerJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerJobRequest.ProtoReflect.Descriptor instead.
func (*TriggerJobRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{11}
}

func (x *TriggerJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TriggerJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerJobResponse) Reset() {
	*x = TriggerJobResponse{}
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerJobResponse) ProtoMessage() {}

func (x *TriggerJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_scheduler_v1_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerJobResponse.ProtoReflect.Descriptor instead.
func (*TriggerJobResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *TriggerJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pkg_api_scheduler_v1_scheduler_proto protoreflect.FileDescriptor

const file_pkg_api_scheduler_v1_scheduler_proto_rawDesc = "" +
	"\n" +
	"$pkg/api/scheduler/v1/scheduler.proto\x12\x10api.scheduler.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x04\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12-\n" +
	"\x04type\x18\x04 \x01(\x0e2\x19.api.scheduler.v1.JobTypeR\x04type\x123\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1b.api.scheduler.v1.JobStatusR\x06status\x12'\n" +
	"\x0fcron_expression\x18\x06 \x01(\tR\x0ecronExpression\x12\x18\n" +
	"\apayload\x18\a \x01(\tR\apayload\x12\x16\n" +
	"\x06target\x18\b \x01(\tR\x06target\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\rnext_run_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vnextRunTime\x12>\n" +
	"\rlast_run_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vlastRunTime\"\xfa\x01\n" +
	"\x10CreateJobRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x129\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.api.scheduler.v1.JobTypeB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\x04type\x120\n" +
	"\x0fcron_expression\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x0ecronExpression\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\x12 \n" +
	"\x06target\x18\x06 \x01(\tB\b\xfaB\x05r\x03\x88\x01\x01R\x06target\"#\n" +
	"\x11CreateJobResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\rGetJobRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"9\n" +
	"\x0eGetJobResponse\x12'\n" +
	"\x03job\x18\x01 \x01(\v2\x15.api.scheduler.v1.JobR\x03job\"M\n" +
	"\x0fListJobsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x86\x01\n" +
	"\x10ListJobsResponse\x12)\n" +
	"\x04jobs\x18\x01 \x03(\v2\x15.api.scheduler.v1.JobR\x04jobs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xf1\x01\n" +
	"\x10UpdateJobRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x0fcron_expression\x18\x04 \x01(\tR\x0ecronExpression\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\x12\x16\n" +
	"\x06target\x18\x06 \x01(\tR\x06target\x123\n" +
	"\x06status\x18\a \x01(\x0e2\x1b.api.scheduler.v1.JobStatusR\x06status\"#\n" +
	"\x11UpdateJobResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x10DeleteJobRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\"#\n" +
	"\x11DeleteJobResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\x11TriggerJobRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\".\n" +
	"\x12TriggerJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*I\n" +
	"\aJobType\x12\x18\n" +
	"\x14JOB_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rJOB_TYPE_HTTP\x10\x01\x12\x11\n" +
	"\rJOB_TYPE_GRPC\x10\x02*X\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_ENABLED\x10\x01\x12\x17\n" +
	"\x13JOB_STATUS_DISABLED\x10\x022\x9e\x05\n" +
	"\x10SchedulerService\x12i\n" +
	"\tCreateJob\x12\".api.scheduler.v1.CreateJobRequest\x1a#.api.scheduler.v1.CreateJobResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/jobs\x12b\n" +
	"\x06GetJob\x12\x1f.api.scheduler.v1.GetJobRequest\x1a .api.scheduler.v1.GetJobResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/jobs/{id}\x12c\n" +
	"\bListJobs\x12!.api.scheduler.v1.ListJobsRequest\x1a\".api.scheduler.v1.ListJobsResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/jobs\x12n\n" +
	"\tUpdateJob\x12\".api.scheduler.v1.UpdateJobRequest\x1a#.api.scheduler.v1.UpdateJobResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\x1a\r/v1/jobs/{id}\x12k\n" +
	"\tDeleteJob\x12\".api.scheduler.v1.DeleteJobRequest\x1a#.api.scheduler.v1.DeleteJobResponse\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/v1/jobs/{id}\x12y\n" +
	"\n" +
	"TriggerJob\x12#.api.scheduler.v1.TriggerJobRequest\x1a$.api.scheduler.v1.TriggerJobResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/jobs/{id}/triggerB@Z>github.com/kart-io/sentinel-x/pkg/api/scheduler/v1;schedulerv1b\x06proto3"

var (
	file_pkg_api_scheduler_v1_scheduler_proto_rawDescOnce sync.Once
	file_pkg_api_scheduler_v1_scheduler_proto_rawDescData []byte
)

func file_pkg_api_scheduler_v1_scheduler_proto_rawDescGZIP() []byte {
	file_pkg_api_scheduler_v1_scheduler_proto_rawDescOnce.Do(func() {
		file_pkg_api_scheduler_v1_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_scheduler_v1_scheduler_proto_rawDesc), len(file_pkg_api_scheduler_v1_scheduler_proto_rawDesc)))
	})
	return file_pkg_api_scheduler_v1_scheduler_proto_rawDescData
}

var file_pkg_api_scheduler_v1_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_api_scheduler_v1_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_api_scheduler_v1_scheduler_proto_goTypes = []any{
	(JobType)(0),                  // 0: api.scheduler.v1.JobType
	(JobStatus)(0),                // 1: api.scheduler.v1.JobStatus
	(*Job)(nil),                   // 2: api.scheduler.v1.Job
	(*CreateJobRequest)(nil),      // 3: api.scheduler.v1.CreateJobRequest
	(*CreateJobResponse)(nil),     // 4: api.scheduler.v1.CreateJobResponse
	(*GetJobRequest)(nil),         // 5: api.scheduler.v1.GetJobRequest
	(*GetJobResponse)(nil),        // 6: api.scheduler.v1.GetJobResponse
	(*ListJobsRequest)(nil),       // 7: api.scheduler.v1.ListJobsRequest
	(*ListJobsResponse)(nil),      // 8: api.scheduler.v1.ListJobsResponse
	(*UpdateJobRequest)(nil),      // 9: api.scheduler.v1.UpdateJobRequest
	(*UpdateJobResponse)(nil),     // 10: api.scheduler.v1.UpdateJobResponse
	(*DeleteJobRequest)(nil),      // 11: api.scheduler.v1.DeleteJobRequest
	(*DeleteJobResponse)(nil),     // 12: api.scheduler.v1.DeleteJobResponse
	(*TriggerJobRequest)(nil),     // 13: api.scheduler.v1.TriggerJobRequest
	(*TriggerJobResponse)(nil),    // 14: api.scheduler.v1.TriggerJobResponse
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_pkg_api_scheduler_v1_scheduler_proto_depIdxs = []int32{
	0,  // 0: api.scheduler.v1.Job.type:type_name -> api.scheduler.v1.JobType
	1,  // 1: api.scheduler.v1.Job.status:type_name -> api.scheduler.v1.JobStatus
	15, // 2: api.scheduler.v1.Job.created_at:type_name -> google.protobuf.Timestamp
	15, // 3: api.scheduler.v1.Job.updated_at:type_name -> google.protobuf.Timestamp
	15, // 4: api.scheduler.v1.Job.next_run_time:type_name -> google.protobuf.Timestamp
	15, // 5: api.scheduler.v1.Job.last_run_time:type_name -> google.protobuf.Timestamp
	0,  // 6: api.scheduler.v1.CreateJobRequest.type:type_name -> api.scheduler.v1.JobType
	2,  // 7: api.scheduler.v1.GetJobResponse.job:type_name -> api.scheduler.v1.Job
	2,  // 8: api.scheduler.v1.ListJobsResponse.jobs:type_name -> api.scheduler.v1.Job
	1,  // 9: api.scheduler.v1.UpdateJobRequest.status:type_name -> api.scheduler.v1.JobStatus
	3,  // 10: api.scheduler.v1.SchedulerService.CreateJob:input_type -> api.scheduler.v1.CreateJobRequest
	5,  // 11: api.scheduler.v1.SchedulerService.GetJob:input_type -> api.scheduler.v1.GetJobRequest
	7,  // 12: api.scheduler.v1.SchedulerService.ListJobs:input_type -> api.scheduler.v1.ListJobsRequest
	9,  // 13: api.scheduler.v1.SchedulerService.UpdateJob:input_type -> api.scheduler.v1.UpdateJobRequest
	11, // 14: api.scheduler.v1.SchedulerService.DeleteJob:input_type -> api.scheduler.v1.DeleteJobRequest
	13, // 15: api.scheduler.v1.SchedulerService.TriggerJob:input_type -> api.scheduler.v1.TriggerJobRequest
	4,  // 16: api.scheduler.v1.SchedulerService.CreateJob:output_type -> api.scheduler.v1.CreateJobResponse
	6,  // 17: api.scheduler.v1.SchedulerService.GetJob:output_type -> api.scheduler.v1.GetJobResponse
	8,  // 18: api.scheduler.v1.SchedulerService.ListJobs:output_type -> api.scheduler.v1.ListJobsResponse
	10, // 19: api.scheduler.v1.SchedulerService.UpdateJob:output_type -> api.scheduler.v1.UpdateJobResponse
	12, // 20: api.scheduler.v1.SchedulerService.DeleteJob:output_type -> api.scheduler.v1.DeleteJobResponse
	14, // 21: api.scheduler.v1.SchedulerService.TriggerJob:output_type -> api.scheduler.v1.TriggerJobResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pkg_api_scheduler_v1_scheduler_proto_init() }
func file_pkg_api_scheduler_v1_scheduler_proto_init() {
	if File_pkg_api_scheduler_v1_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_scheduler_v1_scheduler_proto_rawDesc), len(file_pkg_api_scheduler_v1_scheduler_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_scheduler_v1_scheduler_proto_goTypes,
		DependencyIndexes: file_pkg_api_scheduler_v1_scheduler_proto_depIdxs,
		EnumInfos:         file_pkg_api_scheduler_v1_scheduler_proto_enumTypes,
		MessageInfos:      file_pkg_api_scheduler_v1_scheduler_proto_msgTypes,
	}.Build()
	File_pkg_api_scheduler_v1_scheduler_proto = out.File
	file_pkg_api_scheduler_v1_scheduler_proto_goTypes = nil
	file_pkg_api_scheduler_v1_scheduler_proto_depIdxs = nil
}
